modLoader = "javafml"
loaderVersion="[1,)"
license="${license}"
showAsResourcePack=false

issueTrackerURL = "https://github.com/noramibu/Cerulean/issues"

[[mods]]
modId="${id}"
version="${modversion}"
displayName="${display_name}"
authors="noramibu, Toni, Mephodio"
description="${description}"
logoFile="assets/${namespace}/textures/mod_logo.png"
displayURL = "https://github.com/noramibu/Cerulean/branches"

[[mixins]]
config = "mixins.${mixinid}.json"

[[dependencies."${id}"]]
modId="minecraft"
mandatory=true
versionRange="[1.21.8,)"
ordering="NONE"
side="BOTH"

${depends}
